language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - master

os:
  - linux
  - osx

install:
  - go get ./...
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install eslint eslint-config-strict eslint-plugin-filenames

script:
  - go test -v ./...
  - ./node_modules/eslint/bin/eslint.js js/main.js
