language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - master

node_js:
  - "6"

before_script:
  - npm install eslint eslint-config-strict eslint-plugin-filenames

script:
  - go test -v ./...
  - ./node_modules/eslint/bin/eslint.js js/main.js
