language: go

go:
  - 1.3

before_script:
  - npm install eslint eslint-checker-strict eslint-plugin-filenames
  - go get github.com/gorilla/websocket

script:
  - go test -v ./...
  - ./node_modules/eslint/bin/eslint.js js/main.js
